import React, { useState } from "react";
import "./SuperAdminPanel.css";
import { apiFetch } from "../utils/api";
import Header from "./Header";

const SuperAdminPanel = () => {
  const [form, setForm] = useState({
    // restaurant_id and owner_user_id are generated by backend (UUID), not in form
    name: "",
    address: "",
    latitude: "",
    longitude: "",
    phone_number: "",
    email: "",
    description: "",
    logo_url: "",
    opening_hours: "",
  });
  const [success, setSuccess] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const [showRestaurantForm, setShowRestaurantForm] = useState(true);
  const [userForm, setUserForm] = useState({
    email: "",
    user_type: "",
    name: "",
    phone_number: "",
  });

  const handleChange = (e) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setSuccess("");
    setError("");
    setLoading(true);
    try {
      const response = await apiFetch("/api/addRestausrant", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(form),
      });
      if (response && response.success) {
        setSuccess("Restaurant added successfully!");
        setForm({
          name: "",
          address: "",
          latitude: "",
          longitude: "",
          phone_number: "",
          email: "",
          description: "",
          logo_url: "",
          opening_hours: "",
        });
      } else {
        setError("Failed to add restaurant.");
      }
    } catch (err) {
      setError("Error adding restaurant.");
    }
    setLoading(false);
  };

  const handleUserChange = (e) => {
    setUserForm({ ...userForm, [e.target.name]: e.target.value });
  };

  const handleUserSubmit = async (e) => {
    e.preventDefault();
    setSuccess("");
    setError("");
    setLoading(true);
    try {
      const response = await apiFetch("/api/addUser", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(userForm),
      });
      if (response && response.success) {
        setSuccess("User added successfully!");
        setUserForm({ email: "", user_type: "", name: "", phone_number: "" });
      } else {
        setError("Failed to add user.");
      }
    } catch (err) {
      setError("Error adding user.");
    }
    setLoading(false);
  };

  const handleLogout = () => {
    // Clear any session/token if needed
    window.location.href = "/";
  };

  return (
    <div>
      <Header onLogout={handleLogout} userType="SuperAdmin" />
      <div className="superadmin-panel">
        <h2>Super Admin Panel</h2>
        <div style={{ marginBottom: 20 }}>
          <button
            className={showRestaurantForm ? "active-btn" : ""}
            onClick={() => setShowRestaurantForm(true)}
            style={{ marginRight: 10 }}
          >
            Add Restaurant
          </button>
          <button
            className={!showRestaurantForm ? "active-btn" : ""}
            onClick={() => setShowRestaurantForm(false)}
          >
            Add User
          </button>
        </div>
        {showRestaurantForm ? (
          <form className="restaurant-form" onSubmit={handleSubmit}>
            <input
              name="name"
              value={form.name}
              onChange={handleChange}
              placeholder="Restaurant Name"
              required
            />
            <input
              name="address"
              value={form.address}
              onChange={handleChange}
              placeholder="Address"
              required
            />
            <input
              name="latitude"
              value={form.latitude}
              onChange={handleChange}
              placeholder="Latitude"
              required
              type="number"
              step="any"
            />
            <input
              name="longitude"
              value={form.longitude}
              onChange={handleChange}
              placeholder="Longitude"
              required
              type="number"
              step="any"
            />
            <input
              name="phone_number"
              value={form.phone_number}
              onChange={handleChange}
              placeholder="Phone Number"
              required
            />
            <input
              name="email"
              value={form.email}
              onChange={handleChange}
              placeholder="Email"
            />
            <textarea
              name="description"
              value={form.description}
              onChange={handleChange}
              placeholder="Description"
            />
            <input
              name="logo_url"
              value={form.logo_url}
              onChange={handleChange}
              placeholder="Logo URL"
            />
            <textarea
              name="opening_hours"
              value={form.opening_hours}
              onChange={handleChange}
              placeholder="Opening Hours (JSON format)"
              required
            />
            <button type="submit">Add Restaurant</button>
          </form>
        ) : (
          <form className="user-form" onSubmit={handleUserSubmit}>
            <input
              name="email"
              value={userForm.email}
              onChange={handleUserChange}
              placeholder="Email"
              required
            />
            <select
              name="user_type"
              value={userForm.user_type}
              onChange={handleUserChange}
              required
            >
              <option value="">Select User Type</option>
              <option value="RegularUser">RegularUser</option>
              <option value="Restaurant">Restaurant</option>
              <option value="SuperAdmin">SuperAdmin</option>
            </select>
            <input
              name="name"
              value={userForm.name}
              onChange={handleUserChange}
              placeholder="Name"
              required
            />
            <input
              name="phone_number"
              value={userForm.phone_number}
              onChange={handleUserChange}
              placeholder="Phone Number"
            />
            <button type="submit">Add User</button>
          </form>
        )}
        {success && <div className="success-message">{success}</div>}
        {error && <div className="error-message">{error}</div>}
        {loading && (
          <div className="loading-overlay">
            <div className="loading-spinner"></div>
            <div>Submitting...</div>
          </div>
        )}
      </div>
    </div>
  );
};

export default SuperAdminPanel;
