import React, { useState } from "react";
import "./SuperAdminPanel.css";
import { apiFetch } from "../utils/api";

const SuperAdminPanel = () => {
  const [form, setForm] = useState({
    // restaurant_id is generated by backend (UUID), not in form
    owner_user_id: "",
    name: "",
    address: "",
    latitude: "",
    longitude: "",
    phone_number: "",
    email: "",
    description: "",
    logo_url: "",
    opening_hours: "",
  });
  const [success, setSuccess] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  const handleChange = (e) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setSuccess("");
    setError("");
    setLoading(true);
    try {
      const response = await apiFetch("/api/restaurants", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(form),
      });
      if (response && response.success) {
        setSuccess("Restaurant added successfully!");
        setForm({
          owner_user_id: "",
          name: "",
          address: "",
          latitude: "",
          longitude: "",
          phone_number: "",
          email: "",
          description: "",
          logo_url: "",
          opening_hours: "",
        });
      } else {
        setError("Failed to add restaurant.");
      }
    } catch (err) {
      setError("Error adding restaurant.");
    }
    setLoading(false);
  };

  return (
    <div className="superadmin-panel">
      <h2>Super Admin Panel - Add Restaurant</h2>
      {loading && (
        <div className="loading-overlay">
          <div className="loading-spinner"></div>
          <div>Submitting...</div>
        </div>
      )}
      <form className="restaurant-form" onSubmit={handleSubmit}>
        <input
          name="owner_user_id"
          value={form.owner_user_id}
          onChange={handleChange}
          placeholder="Owner User ID"
          required
        />
        <input
          name="name"
          value={form.name}
          onChange={handleChange}
          placeholder="Restaurant Name"
          required
        />
        <input
          name="address"
          value={form.address}
          onChange={handleChange}
          placeholder="Address"
          required
        />
        <input
          name="latitude"
          value={form.latitude}
          onChange={handleChange}
          placeholder="Latitude"
          required
          type="number"
          step="any"
        />
        <input
          name="longitude"
          value={form.longitude}
          onChange={handleChange}
          placeholder="Longitude"
          required
          type="number"
          step="any"
        />
        <input
          name="phone_number"
          value={form.phone_number}
          onChange={handleChange}
          placeholder="Phone Number"
          required
        />
        <input
          name="email"
          value={form.email}
          onChange={handleChange}
          placeholder="Email"
        />
        <textarea
          name="description"
          value={form.description}
          onChange={handleChange}
          placeholder="Description"
        />
        <input
          name="logo_url"
          value={form.logo_url}
          onChange={handleChange}
          placeholder="Logo URL"
        />
        <textarea
          name="opening_hours"
          value={form.opening_hours}
          onChange={handleChange}
          placeholder="Opening Hours (JSON format)"
          required
        />
        <button type="submit">Add Restaurant</button>
      </form>
      {success && <div className="success-message">{success}</div>}
      {error && <div className="error-message">{error}</div>}
    </div>
  );
};

export default SuperAdminPanel;
