import React, { useState } from "react";
import "./SuperAdminPanel.css";
import { apiFetch } from "../utils/api";
import Header from "./Header";
import Sidebar from "./Sidebar";
import { FaUsers, FaStore, FaUtensils } from "react-icons/fa";

const SuperAdminPanel = () => {
  const [form, setForm] = useState({
    // restaurant_id and owner_user_id are generated by backend (UUID), not in form
    name: "",
    address: "",
    latitude: "",
    longitude: "",
    phone_number: "",
    email: "",
    description: "",
    logo_url: "",
    opening_hours: "",
  });
  const [success, setSuccess] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const [activeForm, setActiveForm] = useState(""); // No form shown initially
  const [userForm, setUserForm] = useState({
    email: "",
    user_type: "",
    name: "",
    phone_number: "",
  });
  const [activeSection, setActiveSection] = useState("dashboard");
  const [showRestaurantsList, setShowRestaurantsList] = useState(false);
  const [restaurantUsers, setRestaurantUsers] = useState([]);
  const [restaurantUsersLoading, setRestaurantUsersLoading] = useState(false);
  const [restaurantUsersError, setRestaurantUsersError] = useState("");

  const handleChange = (e) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setSuccess("");
    setError("");
    setLoading(true);
    try {
      const response = await apiFetch("/api/addRestaurant", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(form),
      });
      if (response && response.success) {
        setSuccess("Restaurant added successfully!");
        setForm({
          name: "",
          address: "",
          latitude: "",
          longitude: "",
          phone_number: "",
          email: "",
          description: "",
          logo_url: "",
          opening_hours: "",
        });
      } else {
        setError("Failed to add restaurant.");
      }
    } catch (err) {
      setError("Error adding restaurant.");
    }
    setLoading(false);
  };

  const handleUserChange = (e) => {
    setUserForm({ ...userForm, [e.target.name]: e.target.value });
  };

  const handleUserSubmit = async (e) => {
    e.preventDefault();
    setSuccess("");
    setError("");
    setLoading(true);
    try {
      const response = await apiFetch("/api/addUser", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(userForm),
      });
      if (response && response.success) {
        setSuccess("User added successfully!");
        setUserForm({ email: "", user_type: "", name: "", phone_number: "" });
      } else {
        setError("Failed to add user.");
      }
    } catch (err) {
      setError("Error adding user.");
    }
    setLoading(false);
  };

  const handleLogout = () => {
    // Clear any session/token if needed
    window.location.href = "/";
  };

  const handleRestaurantsCardClick = () => {
    setShowRestaurantsList(true);
    setRestaurantUsersLoading(true);
    setRestaurantUsersError("");
    apiFetch("/api/getAllUsers")
      .then((response) => {
        if (response && response.success && Array.isArray(response.users)) {
          const filtered = response.users.filter(
            (u) => u.user_type === "Restaurant"
          );
          setRestaurantUsers(filtered);
        } else {
          setRestaurantUsersError("Failed to fetch users.");
        }
        setRestaurantUsersLoading(false);
      })
      .catch(() => {
        setRestaurantUsersError("Error fetching users.");
        setRestaurantUsersLoading(false);
      });
  };

  const handleBackToDashboard = () => {
    setShowRestaurantsList(false);
  };

  // Update form toggling to use sidebar navigation
  React.useEffect(() => {
    if (activeSection === "restaurant" || activeSection === "user") {
      setActiveForm(activeSection);
    } else {
      setActiveForm("");
    }
  }, [activeSection]);

  return (
    <div>
      <Header onLogout={handleLogout} userType="SuperAdmin" />
      <div style={{ display: "flex", minHeight: "100vh" }}>
        <Sidebar
          onLogout={handleLogout}
          activeSection={activeSection}
          setActiveSection={setActiveSection}
        />
        <div className="superadmin-main">
          <h2>Super Admin Panel</h2>
          {/* Dashboard summary cards */}
          {activeSection === "dashboard" && !showRestaurantsList && (
            <div className="dashboard-cards">
              <div className="dashboard-card">
                <FaUsers className="dashboard-icon" />
                <div className="dashboard-card-title">Total Users</div>
                <div className="dashboard-card-value">123</div>
              </div>
              <div
                className="dashboard-card"
                style={{ cursor: "pointer" }}
                onClick={handleRestaurantsCardClick}
              >
                <FaStore className="dashboard-icon" />
                <div className="dashboard-card-title">Restaurants</div>
                <div className="dashboard-card-value">12</div>
              </div>
              <div className="dashboard-card">
                <FaUtensils className="dashboard-icon" />
                <div className="dashboard-card-title">Menu Items</div>
                <div className="dashboard-card-value">56</div>
              </div>
            </div>
          )}
          {activeSection === "dashboard" && showRestaurantsList && (
            <div style={{ marginBottom: 32 }}>
              <button
                onClick={handleBackToDashboard}
                style={{ marginBottom: 16 }}
              >
                Back to Dashboard
              </button>
              <h3>Restaurant Users</h3>
              {restaurantUsersLoading ? (
                <div>Loading...</div>
              ) : restaurantUsersError ? (
                <div className="error-message">{restaurantUsersError}</div>
              ) : restaurantUsers.length === 0 ? (
                <div>No restaurant users found.</div>
              ) : (
                <table
                  style={{
                    width: "100%",
                    background: "#fff",
                    borderRadius: 8,
                    boxShadow: "0 2px 8px rgba(35,41,70,0.06)",
                    marginTop: 12,
                  }}
                >
                  <thead>
                    <tr style={{ background: "#f4f6fb" }}>
                      <th style={{ padding: "10px 8px", textAlign: "left" }}>
                        Name
                      </th>
                      <th style={{ padding: "10px 8px", textAlign: "left" }}>
                        Email
                      </th>
                      <th style={{ padding: "10px 8px", textAlign: "left" }}>
                        Phone
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {restaurantUsers.map((u) => (
                      <tr key={u.user_id}>
                        <td style={{ padding: "8px" }}>{u.name}</td>
                        <td style={{ padding: "8px" }}>{u.email}</td>
                        <td style={{ padding: "8px" }}>{u.phone_number}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              )}
            </div>
          )}
          {/* Form toggles removed, handled by sidebar */}
          {activeForm === "restaurant" && (
            <form className="restaurant-form" onSubmit={handleSubmit}>
              <input
                name="name"
                value={form.name}
                onChange={handleChange}
                placeholder="Restaurant Name"
                required
              />
              <input
                name="address"
                value={form.address}
                onChange={handleChange}
                placeholder="Address"
                required
              />
              <input
                name="latitude"
                value={form.latitude}
                onChange={handleChange}
                placeholder="Latitude"
                required
                type="number"
                step="any"
              />
              <input
                name="longitude"
                value={form.longitude}
                onChange={handleChange}
                placeholder="Longitude"
                required
                type="number"
                step="any"
              />
              <input
                name="phone_number"
                value={form.phone_number}
                onChange={handleChange}
                placeholder="Phone Number"
                required
              />
              <input
                name="email"
                value={form.email}
                onChange={handleChange}
                placeholder="Email"
              />
              <textarea
                name="description"
                value={form.description}
                onChange={handleChange}
                placeholder="Description"
              />
              <input
                name="logo_url"
                value={form.logo_url}
                onChange={handleChange}
                placeholder="Logo URL"
              />
              <textarea
                name="opening_hours"
                value={form.opening_hours}
                onChange={handleChange}
                placeholder="Opening Hours (JSON format)"
                required
              />
              <button type="submit">Add Restaurant</button>
            </form>
          )}
          {activeForm === "user" && (
            <form className="user-form" onSubmit={handleUserSubmit}>
              <input
                name="email"
                value={userForm.email}
                onChange={handleUserChange}
                placeholder="Email"
                required
              />
              <select
                id="user_type_select"
                name="user_type"
                value={userForm.user_type}
                onChange={handleUserChange}
                required
              >
                <option value="" disabled>
                  User Type
                </option>
                <option value="RegularUser">RegularUser</option>
                <option value="SuperAdmin">SuperAdmin</option>
              </select>
              <input
                name="name"
                value={userForm.name}
                onChange={handleUserChange}
                placeholder="Name"
                required
              />
              <input
                name="phone_number"
                value={userForm.phone_number}
                onChange={handleUserChange}
                placeholder="Phone Number"
              />
              <button type="submit">Add User</button>
            </form>
          )}
          {/* Welcome/empty state */}
          {activeSection === "dashboard" && !activeForm && (
            <div className="welcome-message">
              Welcome to the Super Admin Dashboard! Select an option from the
              sidebar to get started.
            </div>
          )}
          {success && <div className="success-message">{success}</div>}
          {error && <div className="error-message">{error}</div>}
          {loading && (
            <div className="loading-overlay">
              <div className="loading-spinner"></div>
              <div>Submitting...</div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default SuperAdminPanel;
